package:
  name: companno
  version: "0.0.4"

source:
  git_url: https://github.com/IC-Induja/CompAnno
  git_rev: v0.0.4

build:
  number: 4

requirements:
  host:
    - python
    - setuptools

  run:
    - python
about:
  summary: Comparative analysis of genome annotations.
  home: https://github.com/IC-Induja/CompAnno
  license: MIT
